### PR TITLE
Replace backslash with forward slash

### PR DESCRIPTION
**Pull request by kekePower**
Hi.
I saw that you've used backslash as a delimiter for "Artist / Album" and, IMHO, it doesn't look good.

This PR replaces the backslashes with a forward slash.

Has been compiled and tested on Mageia 6 successfully.

Cheers,
kekePower

### CODE REVIEW

**Comment by MBach** [comment]
Hi,

Thank you for suggesting this modification. However, I like backslash, so what you should I do :)?

**Comment by kekePower** [comment]
Good morning.
It's really not a question of liking or not liking.
This can be compared to having the left shoe on your right foot and the right shoe on your left foot. Sure, it works, but it just doesn't look right.

Anyway, it is your project and I can choose to either fork it (I won't) or apply my patch to every new version you release or you can live happily ever after knowing you did the Right Thing(tm) :-)

I don't care if you use or discard this PR :-)

Cheers,
kekePower

**Comment by MBach** [comment]
Actually, I think the best solution would be to design this UI with [QDir::separator()](http://doc.qt.io/qt-5.9/qdir.html#separator)

**Comment by kekePower** [comment]
Isn't that one meant for file paths?

I saw in the translations that you had hard coded the backslash in the strings. All of these are changed in my PR.

**Comment by MBach** [comment]
Indeed, it's mostly used for file paths. But you may find a forward slash nicer if you always have been on unix, and find a backslash nicer for Windows users.

**Comment by kekePower** [comment]
But then again, the forward slash is the "standard" delimiter. Found this article a good read.
http://www.buzzle.com/articles/forward-slash-vs-backslash.html

**Pull request merged**
